/*
 * Copyright 2014-2016 CyberVision, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# ifndef KAA_DEFAULTS_H_
# define KAA_DEFAULTS_H_

/**
 *
 * DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED.
 *
 */

# include "kaa_common.h"

# ifdef __cplusplus
extern "C" {
# endif

# define KAA_BUILD_VERSION             "0.9.0"
# define KAA_BUILD_COMMIT_HASH         ""

# define KAA_SDK_TOKEN                 "0zAxdkyHZbBsAnTz5pWb42doVMA"

# define KAA_PROFILE_SCHEMA_VERSION    0


# define KAA_SYNC_TIMEOUT               60000L


/**
 * @brief Uses to represent transport-specific connection data to establish
 * connection to Bootstrap servers.
 *
 * @see kaa_transport_protocol_id_t
 * @see kaa_access_point_t
 */
typedef struct {
    kaa_transport_protocol_id_t    protocol_id;
    kaa_access_point_t             access_point;
} kaa_bootstrap_server_connection_data_t;

# define KAA_BOOTSTRAP_ACCESS_POINT_COUNT    2

static const kaa_bootstrap_server_connection_data_t KAA_BOOTSTRAP_ACCESS_POINTS[KAA_BOOTSTRAP_ACCESS_POINT_COUNT] =
{
    {
        { 0xfb9a3cf0, 1 },
        {
            0x929a2016,
            319,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -100 , 20 , -71 , 87 , -24 , -46 , 96 , 31 , 122 , -95 , 70 , -74 , 35 , -19 , -52 , 68 , -89 , 25 , 73 , -46 , 29 , 36 , -116 , 113 , 13 , -28 , -59 , -110 , -25 , 62 , 46 , 15 , -13 , 41 , -40 , -13 , 127 , -82 , -128 , 85 , -70 , -125 , -14 , 52 , -117 , -6 , -50 , -89 , 117 , 43 , 119 , -36 , 125 , 63 , -42 , -128 , 97 , -103 , -86 , -90 , 14 , -98 , -76 , 105 , 81 , 104 , 9 , -65 , -29 , -95 , 79 , 34 , -92 , 108 , -60 , -41 , 19 , 52 , 40 , 31 , -27 , -7 , 27 , -67 , -60 , -111 , 110 , 58 , -120 , -39 , 87 , -123 , 81 , -127 , 119 , -38 , -60 , -58 , -87 , -14 , -2 , 85 , 8 , 101 , 92 , 75 , -65 , -49 , -114 , -88 , 125 , -69 , 34 , -93 , 127 , 113 , -101 , 58 , 121 , -12 , 54 , -13 , -29 , 24 , 110 , 23 , 55 , -51 , 98 , 3 , -112 , -23 , 114 , 59 , 99 , 12 , 11 , 92 , -112 , 68 , -47 , 36 , 53 , -113 , -120 , 123 , 49 , 118 , -99 , 55 , 72 , -22 , 77 , -114 , 116 , 0 , 58 , -15 , -106 , -39 , 63 , -8 , -42 , 12 , -108 , 57 , 99 , -108 , 69 , 10 , -113 , -51 , 126 , 34 , -95 , 0 , 43 , 12 , 107 , -46 , 9 , 20 , 114 , -85 , 122 , -98 , 8 , 105 , 103 , 18 , -14 , -36 , -60 , -23 , 118 , 73 , -121 , -11 , -125 , 40 , 63 , 79 , -111 , 56 , -35 , 114 , -16 , -32 , 103 , 84 , -102 , -80 , 62 , -107 , -124 , 78 , 108 , 57 , 39 , 54 , -87 , -87 , -18 , 34 , -99 , -114 , 48 , -54 , -113 , -52 , 17 , -12 , -33 , 55 , -100 , 100 , -40 , -72 , -88 , 5 , -79 , -70 , 96 , -79 , -32 , 110 , 32 , 41 , 33 , 99 , -115 , -47 , -54 , 120 , -56 , 115 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 13 , 56 , 56 , 46 , 56 , 53 , 46 , 50 , 50 , 52 , 46 , 49 , 48 , 55 , 0 , 0 , 38 , -95             }
        }
    },
    {
        { 0x56c8ff92, 1 },
        {
            0x929a2016,
            319,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -100 , 20 , -71 , 87 , -24 , -46 , 96 , 31 , 122 , -95 , 70 , -74 , 35 , -19 , -52 , 68 , -89 , 25 , 73 , -46 , 29 , 36 , -116 , 113 , 13 , -28 , -59 , -110 , -25 , 62 , 46 , 15 , -13 , 41 , -40 , -13 , 127 , -82 , -128 , 85 , -70 , -125 , -14 , 52 , -117 , -6 , -50 , -89 , 117 , 43 , 119 , -36 , 125 , 63 , -42 , -128 , 97 , -103 , -86 , -90 , 14 , -98 , -76 , 105 , 81 , 104 , 9 , -65 , -29 , -95 , 79 , 34 , -92 , 108 , -60 , -41 , 19 , 52 , 40 , 31 , -27 , -7 , 27 , -67 , -60 , -111 , 110 , 58 , -120 , -39 , 87 , -123 , 81 , -127 , 119 , -38 , -60 , -58 , -87 , -14 , -2 , 85 , 8 , 101 , 92 , 75 , -65 , -49 , -114 , -88 , 125 , -69 , 34 , -93 , 127 , 113 , -101 , 58 , 121 , -12 , 54 , -13 , -29 , 24 , 110 , 23 , 55 , -51 , 98 , 3 , -112 , -23 , 114 , 59 , 99 , 12 , 11 , 92 , -112 , 68 , -47 , 36 , 53 , -113 , -120 , 123 , 49 , 118 , -99 , 55 , 72 , -22 , 77 , -114 , 116 , 0 , 58 , -15 , -106 , -39 , 63 , -8 , -42 , 12 , -108 , 57 , 99 , -108 , 69 , 10 , -113 , -51 , 126 , 34 , -95 , 0 , 43 , 12 , 107 , -46 , 9 , 20 , 114 , -85 , 122 , -98 , 8 , 105 , 103 , 18 , -14 , -36 , -60 , -23 , 118 , 73 , -121 , -11 , -125 , 40 , 63 , 79 , -111 , 56 , -35 , 114 , -16 , -32 , 103 , 84 , -102 , -80 , 62 , -107 , -124 , 78 , 108 , 57 , 39 , 54 , -87 , -87 , -18 , 34 , -99 , -114 , 48 , -54 , -113 , -52 , 17 , -12 , -33 , 55 , -100 , 100 , -40 , -72 , -88 , 5 , -79 , -70 , 96 , -79 , -32 , 110 , 32 , 41 , 33 , 99 , -115 , -47 , -54 , 120 , -56 , 115 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 13 , 56 , 56 , 46 , 56 , 53 , 46 , 50 , 50 , 52 , 46 , 49 , 48 , 55 , 0 , 0 , 38 , -96             }
        }
    }};



# define KAA_CONFIGURATION_DATA_LENGTH    17

static const char KAA_CONFIGURATION_DATA[KAA_CONFIGURATION_DATA_LENGTH] =
{
0 , -42 , 107 , -33 , 1 , -94 , 74 , 78 , 106 , -67 , -14 , -87 , -28 , -57 , 18 , -16 , -78 };

# ifdef __cplusplus
} // extern "C"
# endif

# endif /* KAA_DEFAULTS_H_ */

